"""


Classes:
    TextValidator: A class for validating text generated by modules in a subnet.

Functions:
    set_weights: Blockchain call to set weights for miners based on their scores.
    cut_to_max_allowed_weights: Cut the scores to the maximum allowed weights.
    extract_address: Extract an address from a string.
    get_subnet_netuid: Retrieve the network UID of the subnet.
    get_ip_port: Get the IP and port information from module addresses.

Constants:
    IP_REGEX: A regular expression pattern for matching IP addresses.
"""

import asyncio
import concurrent.futures
import functools
import re
import time
from datetime import datetime
from functools import partial
import json
from typing import Optional

from communex.client import CommuneClient  # type: ignore
from communex.module.client import ModuleClient  # type: ignore
from communex.module.module import Module  # type: ignore
from communex.types import Ss58Address  # type: ignore
from substrateinterface import Keypair  # type: ignore

from dippy_validation_api.request import get_model_score
from ._config import ValidatorSettings
from subnet.utils import log
from subnet.common.node_entry import NodeEntry
from ..common.registry_client import RegistryClient
from ..common.score_client import ScoreClient

REGISTRY_KEY = "5Exsj2WLrVqAeoRKPKGKmAX3HCsiPwb4LNy6975xCJUKWMp7"

IP_REGEX = re.compile(r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d+")

def set_weights(
    settings: ValidatorSettings,
    score_dict: dict[
        int, float
    ],  # implemented as a float score from 0 to 1, one being the best
    # you can implement your custom logic for scoring
    netuid: int,
    client: CommuneClient,
    key: Keypair,
) -> Optional[bool]:
    """
    Set weights for miners based on their scores.

    Args:
        score_dict: A dictionary mapping miner UIDs to their scores.
        netuid: The network UID.
        client: The CommuneX client.
        key: The keypair for signing transactions.
    """
    try:
        # you can replace with `max_allowed_weights` with the amount your subnet allows
        score_dict = cut_to_max_allowed_weights(score_dict, settings.max_allowed_weights)

        # Create a new dictionary to store the weighted scores
        weighted_scores: dict[int, int] = {}

        # Calculate the sum of all inverted scores
        scores = sum(score_dict.values())

        # process the scores into weights of type dict[int, int]
        # Iterate over the items in the score_dict
        for uid, score in score_dict.items():
            # Calculate the normalized weight as an integer
            weight = int(score * 1000 / scores)

            # Add the weighted score to the new dictionary
            weighted_scores[uid] = weight

        # filter out 0 weights
        weighted_scores = {k: v for k, v in weighted_scores.items() if v != 0}

        uids = list(weighted_scores.keys())
        weights = list(weighted_scores.values())
        # send the blockchain call

        client.vote(key=key, uids=uids, weights=weights, netuid=netuid)
        return True
    except Exception as e:
        return False


def cut_to_max_allowed_weights(
    score_dict: dict[int, float], max_allowed_weights: int
) -> dict[int, float]:
    """
    Cut the scores to the maximum allowed weights.

    Args:
        score_dict: A dictionary mapping miner UIDs to their scores.
        max_allowed_weights: The maximum allowed weights (default: 420).

    Returns:
        A dictionary mapping miner UIDs to their scores, where the scores have been cut to the maximum allowed weights.
    """
    # sort the score by highest to lowest
    sorted_scores = sorted(score_dict.items(), key=lambda x: x[1], reverse=True)

    # cut to max_allowed_weights
    cut_scores = sorted_scores[:max_allowed_weights]

    return dict(cut_scores)


def extract_address(string: str):
    """
    Extracts an address from a string.
    """
    return re.search(IP_REGEX, string)


def get_ip_port(modules_adresses: dict[int, str]):
    """
    Get the IP and port information from module addresses.

    Args:
        modules_addresses: A dictionary mapping module IDs to their addresses.

    Returns:
        A dictionary mapping module IDs to their IP and port information.
    """

    filtered_addr = {id: extract_address(addr) for id, addr in modules_adresses.items()}
    ip_port = {
        id: x.group(0).split(":") for id, x in filtered_addr.items() if x is not None
    }
    return ip_port


class DippyValidator(Module):
    """
    A class for validating text generated by modules in a subnet.

    Attributes:
        client: The CommuneClient instance used to interact with the subnet.
        key: The keypair used for authentication.
        netuid: The unique identifier of the subnet.
        val_model: The validation model used for scoring answers.
        call_timeout: The timeout value for module calls in seconds (default: 60).

    Methods:
        get_modules: Retrieve all module addresses from the subnet.
        _get_miner_prediction: Prompt a miner module to generate an answer to the given question.
        _score_miner: Score the generated answer against the validator's own answer.
        get_miner_prompt: Generate a prompt for the miner modules.
        validate_step: Perform a validation step by generating questions, prompting modules, and scoring answers.
        validation_loop: Run the validation loop continuously based on the provided settings.
    """

    def __init__(
        self,
        key: Keypair,
        netuid: int,
        client: CommuneClient,
        registry_address: str = "",
        call_timeout: int = 60,
    ) -> None:
        super().__init__()
        self.self_uid = None
        self.client = client
        self.key = key
        self.netuid = netuid
        self.registry_address = registry_address
        self.call_timeout = call_timeout
        self.settings: ValidatorSettings = ValidatorSettings()
        rc = RegistryClient(self.key, True)
        self.registry_client = rc.module_client()
        self.registry_client_key = rc.destination_key
        self.score_client = ScoreClient()


    def _get_miner_scores(self,
                          modules_entries: dict[int, NodeEntry],
                          ) -> dict[int, NodeEntry]:
        for uid, entry in modules_entries.items():
            score = self._get_miner_full_score(entry)
            modules_entries[uid].initial_score = score
            modules_entries[uid].tz_update()
        return modules_entries


    def _get_miner_full_score(self, entry: NodeEntry) -> float:
        score = 0.0
        try:
            score = get_model_score(
                namespace=entry.submission_data["namespace"],
                name=entry.submission_data["name"],
                hash=entry.submission_data["hash"],
                template=entry.submission_data["template"],)
        except Exception as e:
            print(e)
        return score



    async def _get_miner_submissions(
        self,
        modules_entries: dict[int, NodeEntry],
        anything=None,
    ) -> dict[int, NodeEntry]:
        """
        Prompt a miner module to generate an answer to the given question.

        Args:
            question: The question to ask the miner module.
            miner_info: A tuple containing the miner's connection information and key.

        Returns:
            The generated answer from the miner module, or None if the miner fails to generate an answer.
        """
        for uid, entry in modules_entries.items():
            try:
                submission = await self.registry_client.call(
                    fn="get_entry",
                    target_key=self.registry_client_key,
                    params={"key": entry.hotkey},
                    timeout=self.call_timeout,
                )
                print(f"received submission: {submission}")
                if submission is None:
                    continue
                dt = datetime.fromisoformat(submission["time"])
                model_info = json.loads(submission["data"])
                modules_entries[uid].submission_time = dt
                modules_entries[uid].submission_data = model_info
            except Exception as e:
                log(f"Miner failed to generate an answer {str(e)}")
        return modules_entries

    def _score_miner(self, miner_answer: str | None) -> float:

        # Implement your custom scoring logic here
        if not miner_answer:
            return 0

        return 0

    async def validate_step(self, netuid: int, settings: ValidatorSettings) -> None:
        """
        Perform a validation step.

        Generates questions based on the provided settings, prompts modules to generate answers,
        and scores the generated answers against the validator's own answers.

        Args:
            netuid: The network UID of the subnet.
        """

        print(f"start valdiation step : {netuid} and {settings}")
        """
        Retrieve the miner information for the netuid. 
        We perform this step synchronously so no need to worry about fetching stale miners
        """
        module_addresses = self.client.query_map_address(netuid)
        modules_keys = self.client.query_map_key(netuid)
        val_ss58 = self.key.ss58_address
        for uid, ss58key in modules_keys.items():
            if ss58key == val_ss58:
                self.self_uid = uid
        if not self.self_uid:
            raise RuntimeError(f"validator key {val_ss58} is not registered in subnet")

        modules_info: dict[int, tuple[list[str], Ss58Address]] = {}
        # Maps uid to hotkey + ip + port
        modules_entries: dict[int, NodeEntry] = {}

        modules_filtered_address = get_ip_port(module_addresses)
        for uid in modules_keys.keys():
            module_addr = modules_filtered_address.get(uid, None)
            if not module_addr:
                continue
            modules_entries[uid] = NodeEntry(
                hotkey=modules_keys[uid],
                ip=module_addr[0],
                port=int(module_addr[1]),
            )
            modules_info[uid] = (module_addr, modules_keys[uid])
        modules_entries = await self._get_miner_submissions(modules_entries)
        modules_entries = self._get_miner_scores(modules_entries)
        score_dict = self.score_client.normalize_scores(modules_entries)
        for k, v in score_dict.items():
            log(f"score {k} : {v} ")
        # Cannot set self weight
        del score_dict[self.self_uid]
        # the blockchain call to set the weights
        success = set_weights(settings, score_dict, self.netuid, self.client, self.key)
        if success:
            log(f"Set weights : {score_dict}")

    def validation_loop(self, vali_settings: ValidatorSettings) -> None:
        """
        Run the validation loop continuously based on the provided settings.

        Args:
            vali_settings: The validator settings to use for the validation loop.
        """

        while True:
            start_time = time.time()
            _ = asyncio.run(self.validate_step(self.netuid, vali_settings))

            elapsed = time.time() - start_time
            if elapsed < vali_settings.iteration_interval:
                sleep_time = vali_settings.iteration_interval - elapsed
                log(f"Sleeping for {sleep_time}")
                time.sleep(sleep_time)
